<a href="https://colab.research.google.com/github/kritsid/tensorflow/blob/master/Tensorflow2_basics(variables%2Cstrings_and_operators).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
import numpy as np

In [0]:
tf.__version__

'2.2.0'

In [0]:
tensovar = tf.constant([1,2])

In [0]:
tensovar

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [0]:
tensovar.numpy()

array([1, 2], dtype=int32)

In [0]:
tensovar.shape

TensorShape([2])

In [0]:
tensovar.numpy()#output with help of numpy()

array([1, 2], dtype=int32)

In [0]:
#create a numpy array
nparray = np.array([1,2,3,4])
nparray

array([1, 2, 3, 4])

In [0]:
#converting np array to tf array
tensort_array = tf.constant(nparray)

In [0]:
tensort_array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [0]:
# VARIabLES

In [0]:
var1 = tf.Variable([1,2,3,4])

In [0]:
var1

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [0]:
var1.numpy()

array([1, 2, 3, 4], dtype=int32)

In [0]:
var1[0].assign(100)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([100,   2,   3,   4], dtype=int32)>

In [0]:
var1

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([100,   2,   3,   4], dtype=int32)>

In [0]:
tensor = tf.constant(([1,2,3,4,5]))

In [0]:
tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [0]:
tensor +2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 4, 5, 6, 7], dtype=int32)>

In [0]:
tensor *2#2,4,6,8,10

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10], dtype=int32)>

In [0]:
np.square(tensor)#squares each element of tensor

array([ 1,  4,  9, 16, 25], dtype=int32)

In [0]:
np.sqrt(tensor)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [0]:
tensor * tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25], dtype=int32)>

In [0]:
np.dot(tensor,var1)#tensor is 1 2 3 4 5              var1 is 100 2 3 4 we got 5cross 4 array

array([<tf.Tensor: shape=(4,), dtype=int32, numpy=array([100,   2,   3,   4], dtype=int32)>,
       <tf.Tensor: shape=(4,), dtype=int32, numpy=array([200,   4,   6,   8], dtype=int32)>,
       <tf.Tensor: shape=(4,), dtype=int32, numpy=array([300,   6,   9,  12], dtype=int32)>,
       <tf.Tensor: shape=(4,), dtype=int32, numpy=array([400,   8,  12,  16], dtype=int32)>,
       <tf.Tensor: shape=(4,), dtype=int32, numpy=array([500,  10,  15,  20], dtype=int32)>],
      dtype=object)

In [0]:
str = tf.constant("123")
str

<tf.Tensor: shape=(), dtype=string, numpy=b'123'>

In [0]:
tf.strings.unicode_decode(str,"UTF8")
# Decodes each string in input into a sequence of Unicode code points.

# result[i1...iN, j] is the Unicode codepoint for the jth character in input[i1...iN], when decoded using input_encoding.

# Args:

#   input: An `N` dimensional potentially ragged `string` tensor with shape  
#     `[D1...DN]`.  `N` must be statically known.  
#   input_encoding: String name for the unicode encoding that should be used to  
#     decode each string.  

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([49, 50, 51], dtype=int32)>

In [0]:
tf.strings.length(str)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [0]:
str2 = tf.constant(['jhjhj','jjkjk','uioiuio'])

In [0]:
for s in str2:
  print(s)

tf.Tensor(b'jhjhj', shape=(), dtype=string)
tf.Tensor(b'jjkjk', shape=(), dtype=string)
tf.Tensor(b'uioiuio', shape=(), dtype=string)
